### ISSUE TITLE
Columns & Grid Options

### ISSUE THREAD

**Issue by 4d5452** [formio/ngFormioGrid#20]
How should columnDefs and columns be defined?  When using templates/resource/index.html provided by the formio-helper module, currentResource.columns and currentResource.gridOptions are passed to the formio-grid directive.

ColumnDef declaration...
`$scope.currentResource.gridOptions={
            columnDefs:[ { displayName:'Filter ID',
                field:'data.filterId'
            }]
};`

but,  I'm unable to attach links within the columnDefinition.  To do so, add a  column to currentResources.columns.

Columns...
`$scope.currentResource.columns=[
            {
              key:'data.filterId',
              label: 'Filter ID',
              link: true
            }
          ];`

However, if columnDefs is defined, then currentResource.columns has no effect on the dom, and the link does not exist.

**Comment by LeMamin** [comment]
For the moment you can redefine the column template : 
   ```
var template = '<formio-grid-cell class="ui-grid-cell-contents" data="COL_FIELD" component="col.colDef.component"></formio-grid-cell>';
          $scope.currentResource.gridOptions = {
            columnDefs: [
              {
                cellTemplate: '<a style="cursor:pointer;" ng-click="grid.appScope.buttonClick(\'rowView\', row)">' + template + '</a>',
                displayName: 'Prénom',
                enableFiltering: true,
                field: 'data.firstName'
              },
              {
                displayName: 'Nom',
                enableFiltering: true,
                field: 'data.lastName'
              },
             ...
            ]
          };
```
